apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: systesting-prepare-env
spec:
  params:
    - name: run-id
      type: string
  workspaces:
  - name: manifest
    mountPath: /adhoc-manifests
  steps:
  - name: generate-manifest
    image: hub.pingcap.net/qa/kubetools:20200730
    script: |
      #!/usr/bin/env bash
      echo "generating resources manifest..."
      cat <<EOF > "$(workspaces.manifest.path)/resources.yaml"
      apiVersion: naglfar.pingcap.com/v1
      kind: TestResourceRequest
      metadata:
        name: $(params.run-id)
      spec:
        items:
          - name: db
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 10GB
                  mountPath: /disks1
          - name: kv1
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 200GB
                  mountPath: /disks1
          - name: kv2
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 200GB
                  mountPath: /disks1
          - name: kv3
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 200GB
                  mountPath: /disks1
          - name: kv4
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 200GB
                  mountPath: /disks1
          - name: kv5
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 200GB
                  mountPath: /disks1
          - name: pd
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 20GB
                  mountPath: /disks1
          - name: ctl
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 200GB
                  mountPath: /disks1
          - name: workload
            spec:
              memory: 8GB
              cores: 8
              disks:
                disk1:
                  kind: nvme
                  size: 10GB
                  mountPath: /disks1
      EOF
      echo "generating resources manifest...done"
      cat "$(workspaces.manifest.path)/resources.yaml"

      echo "generating cluster manifest..."
      cat <<EOF > "$(workspaces.manifest.path)/cluster.yaml"
      apiVersion: naglfar.pingcap.com/v1
      kind: TestClusterTopology
      metadata:
        name: $(params.run-id)
      spec:
        resourceRequest: $(params.run-id)
        tidbCluster:
          global:
            deployDir: "/disks1/deploy"
            dataDir: "/disks1/data"
          version:
            version: nightly
          control: ctl
          tikv:
            - host: kv1
            - host: kv2
            - host: kv3
          tidb:
            - host: db
          pd:
            - host: pd
          monitor:
            - host: ctl
          grafana:
            - host: ctl
              port: 9000
      EOF
      echo "generating cluster manifest...done"
      cat "$(workspaces.manifest.path)/cluster.yaml"
  - name: apply-resources
    image: hub.pingcap.net/qa/kubetools:20200730
    script: |
      #!/usr/bin/env bash
      kubectl apply -f "$(workspaces.manifest.path)/resources.yaml"
      kubectl apply -f "$(workspaces.manifest.path)/cluster.yaml"
  - name: wait-until-cluster-started
    image: hub.pingcap.net/qa/kubetools:20200730
    script: |
      #!/usr/bin/env bash
      while true
      do
        state=`kubectl get tct "$(params.run-id)" -ojsonpath='{.status.state}' || echo unknown`
        echo "current resource state: $state"
        if [ "ready" = "$state" ]; then
            break
        fi
        echo "test resources isn't ready now, wait another 10s..."
        sleep 10
      done
