apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: st--workload-tpcc--restore
spec:

  params:
    - name: run-id
      type: string
    - name: tpcc-data-uri
      type: string
      default: "s3://benchmark/tpcc-10-nightly"
  workspaces:
  - name: manifest
    mountPath: /adhoc-manifests

  steps:
  - name: generate-restore-manifest
    image: hub.pingcap.net/qa/kubetools:20200730
    script: |
      #!/usr/bin/env bash
      echo "generating worload manifest..."
      cat <<EOF > "$(workspaces.manifest.path)/restore.yaml"
      apiVersion: naglfar.pingcap.com/v1
      kind: TestWorkload
      metadata:
        name: "$(params.run-id)"
      spec:
        clusterTopologies:
          - name: "$(params.run-id)"
            aliasName: cluster
        workloads:
          - name: "$(params.run-id)"
            dockerContainer:
              resourceRequest:
                name: "$(params.run-id)"
                node: workload
              image: hub.pingcap.net/mahjonp/bench-toolset
              imagePullPolicy: Always
              command:
                - /bin/bash
                - -c
                - |
                  set -x
                  export AWS_ACCESS_KEY_ID=minioadmin
                  export AWS_SECRET_ACCESS_KEY=minioadmin
                  tidbHost=\`echo \$cluster_tidb0 | awk -F ":" '{print \$1}'\`
                  pdHost=\`echo \$cluster_pd0 | awk -F ":" '{print \$1}'\`
                  isTpccExist=\`mysql -uroot -P4000 -h "\$tidbHost" -e "use test; show tables;" | grep customer > /dev/null && echo "yes" || echo "no"\`
                  if [ "\$isTpccExist" == "no" ]; then
                    # mysql -uroot -P4000 -h "\$tidbHost" -e "create database tpcc;"
                    echo "\`date\` restore..."

                    # go-tpc -H \$tidbHost -P4000 -D tpcc tpcc prepare --warehouses 10

                    # sql="restore database * from '$(params.tpcc-data-uri)/?endpoint=http://minio.pingcap.net:9000&access-key=minioadmin&secret-access-key=minioadmin&force-path-style=true';"
                    # mysql -uroot -h \$tidbHost -P4000 -e "\$sql"

                    br -V
                    br restore full --pd="\$pdHost:2379" --storage "$(params.tpcc-data-uri)/" \
                       --s3.endpoint http://minio.pingcap.net:9000 --send-credentials-to-tikv=true

                    ls /tmp/br.log*
                    cat /tmp/br.log*

                    echo "\`date\` restore...done"
                  else
                    echo "database tpcc already exists"
                  fi

      EOF
      echo "generating worload manifest...done"
      cat "$(workspaces.manifest.path)/restore.yaml"
  - name: workload-tail-f
    image: hub.pingcap.net/qa/kubetools:20200730
    script: |
      #!/usr/bin/env bash
      set -xe
      twName="$(params.run-id)"
      echo "ensure test-workload($twName) does not exists"
      exists=`kubectl get tw $twName >/dev/null && echo "yes" || echo "no"`
      if [ "$exists" == "yes" ]; then
        echo "test workload($twName) already exists, delete it."
        kubectl delete tw $twName
      fi

      echo "create test-workload($twName)..."
      kubectl apply -f "$(workspaces.manifest.path)/restore.yaml"
      while true
      do
        state=`kubectl get tw "$twName" -ojsonpath='{.status.state}' || echo pending`
        echo "current workload state: $state"
        if [ "succeeded" == "$state" ]; then
          break
        elif [ "failed" == "$state" ]; then
          break
        elif [ "running" == "$state" ]; then
          break
        fi
        echo "workload wait another 5s"
        sleep 5
      done
      curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/PingCAP-QE/Naglfar/master/scripts/kubectl-naglfar-installer.sh | sh
      ~/.Naglfar/bin/naglfar logs $twName -n $(context.taskRun.namespace) --follow
      kubectl delete tw $twName
