apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: systesting-demo-
spec:
  serviceAccountName: system-testing
  pipelineRef:
    name: systesting
  workspaces:
    - name: manifest
      emptyDir: {}
  params:
    - name: run-id
      value: systesting-demo
  timeout: "2h"
